config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete '/articles/:id', to: 'articles#destroy'
  put '/articles/:id', to: 'articles#update'
  get '/articles/:id/edit', to: 'articles#edit'
  post '/articles', to: 'articles#create'
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  get '/articles/:id', to: 'articles#show', as: :article
  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_params)

    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(articles_params)
      redirect_to articles_path
    else 
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
  def articles_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form|%>
<%= form.label :title %>
<%= form.text_field :title %>
<%= form.label :content %>
<%= form.text_area :content %>
<%= form.submit %>
<% end %>

app/views/articles/delete.html.erb
<h1>Delete Article</h1>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>This is the index page</h1>
.<ul>
  <% @articles.each do | article | %>
    <a href="/articles/<%= article.id %>">
    <strong><%= article.title %></strong>
    <p><%= article.content %></p>
    <%= link_to 'Show', article_path(article.id) %>
    <%= button_to 'Delete', article_path(article.id), method: :delete%>
  <% end %>
</ul>

<%= link_to 'New', articles_new_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<strong><%= @article.title %></strong>
<p><%= @article.content %></p>
<%= link_to 'HomePage', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>